add track_script option [WIP]
salt-formulas/salt-formula-keepalived pull request #10
Opened 2017-02-21 13:17 UTC by epcim

don't merge until title has WIP

2017-03-03 11:56 UTC, cznewt requested changes
Please add README notion as well :) - pillar examples

2017-03-03 13:16 UTC, cznewt approved these changes

2017-03-04 08:58 UTC, merged

2017-03-24 09:32 UTC, kam1kaze commented
@epcim 

I would like to add the common vrrp script that could be used in most cases. It is parametrised, but current formula does not allow to use params :( What do you think about this?


```
❯ cat keepalived/files/vrrp_script_common.sh
#!/usr/bin/env bash

set -o pipefail
set -o nounset
set -o errexit

proc_name="$1" # Example: 'haproxy'
restart_command="${2:-NONE}" # Example: 'service haproxy restart'
wait_seconds="${3:-1}" # how long checks the process after restart atempt

function check_service() {
  pidof "$1"
}

function logging() {
  logger -t "keepalived_vrrp_script[$$]" "$1"
}

if ! check_service "$proc_name"; then

  # tring to fix proxy server if neccessary
  if [[ "$restart_command" != 'NONE' ]]; then
    logging "NOTICE: could not find running '${proc_name}' process, executing '${restart_command}'"
    $restart_command
    for ((s=0; s <= wait_seconds; s++)); do
      sleep $s
      if check_service "$proc_name"; then
        logging "OK: process '$proc_name' succesfully started"
        exit 0
      fi
    done
    logging "FAIL: process '$proc_name' could not be started after $wait_seconds seconds"
    exit 1
  fi

  # return erorr
  logging "FAIL: process '$proc_name' is not running"
  exit 1
fi

logging "OK: process '$proc_name' is running"
exit 0
```

2017-04-26 09:31 UTC, epcim commented
[**@kam1kaze**](https://github.com/kam1kaze) commented on [Mar 24, 2017, 10:32 AM GMT+1](https://github.com/salt-formulas/salt-formula-keepalived/pull/10#issuecomment-288974521 "2017-03-24T09:32:17Z - Replied by Github Reply Comments"):
> @epcim 
> 
> I would like to add the common vrrp script that could be used in most cases. It is parametrised, but current formula does not allow to use params :( What do you think about this?
> 
> 
> ```
> ❯ cat keepalived/files/vrrp_script_common.sh
> #!/usr/bin/env bash
> 
> set -o pipefail
> set -o nounset
> set -o errexit
> 
> proc_name="$1" # Example: 'haproxy'
> restart_command="${2:-NONE}" # Example: 'service haproxy restart'
> wait_seconds="${3:-1}" # how long checks the process after restart atempt
> 
> function check_service() {
>   pidof "$1"
> }
> 
> function logging() {
>   logger -t "keepalived_vrrp_script[$$]" "$1"
> }
> 
> if ! check_service "$proc_name"; then
> 
>   # tring to fix proxy server if neccessary
>   if [[ "$restart_command" != 'NONE' ]]; then
>     logging "NOTICE: could not find running '${proc_name}' process, executing '${restart_command}'"
>     $restart_command
>     for ((s=0; s <= wait_seconds; s++)); do
>       sleep $s
>       if check_service "$proc_name"; then
>         logging "OK: process '$proc_name' succesfully started"
>         exit 0
>       fi
>     done
>     logging "FAIL: process '$proc_name' could not be started after $wait_seconds seconds"
>     exit 1
>   fi
> 
>   # return erorr
>   logging "FAIL: process '$proc_name' is not running"
>   exit 1
> fi
> 
> logging "OK: process '$proc_name' is running"
> exit 0
> ```

Well I would fisrt see script that only check health check for the service. It's not case of this script to restart the service.